version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Add any environment variables your Next.js app needs here
      # For example:
      # NEXT_PUBLIC_API_URL: "http://localhost:8000/api"
      NODE_ENV: production
    # Optional: volumes for local development to enable hot-reloading
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    restart: unless-stopped
